---

- name: Copy license file
  hosts: W*-R*:E*-R*:S*-R*
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Install license
    eos_command:
      commands:
        - "license import flash:ipsec-license.json"
        - "license update"

